#!/usr/bin/env bash

# Detect the installation directory
INSTALLDIR=$PWD

if [ -x "$INSTALLDIR/jdk/bin/java" ]; then
 JAVA_CMD=$INSTALLDIR/jdk/bin/java
else
 echo "Run this program from the installation directory."
 exit 1
fi

"$JAVA_CMD" -jar java-bean-journey-1.0.jar "$@"

# Exit using the same code returned from Java
exit $?