name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  GetJavaFiles:
    runs-on: ubuntu-latest
    outputs:
      java_files: ${{ steps.get-diff.outputs.java_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Java file differences
        id: get-diff
        run: |
          current_branch=$(echo ${GITHUB_HEAD_REF#refs/heads/})
          git fetch origin main
          git fetch origin $current_branch
          java_files=$(git diff --name-only --diff-filter=d origin/main | grep '\.java$' || true)
          echo "::set-output name=java_files::$java_files"
          echo "Files found: $java_files"

  CompileJavaFiles:
    needs: GetJavaFiles
    runs-on: ubuntu-latest
    if: ${{ needs.GetJavaFiles.outputs.java_files != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile Java files
        run: |
          for java_file in ${{ needs.GetJavaFiles.outputs.java_files }}; do
            echo "Compiling $java_file"
            javac "$java_file"
          done
