name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile Java files
        run: |
          git fetch origin main
          javac $(git diff --name-only origin/main...feature-branch | grep '\.java$')

