name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  VerifyChangedCode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile Java files
        run: |
          current_branch=$(echo ${GITHUB_HEAD_REF#refs/heads/})
          git fetch origin main
          git fetch origin $current_branch
          echo "testing compilation for:"
          echo $(git diff --name-only origin/main | grep '\.java$')
          javac $(git diff --name-only origin/main | grep '\.java$')




