name: Release

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  package:
    uses: FreeTheBeans/java-bean-journey/.github/workflows/package.yml@release

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download releases
        uses: actions/download-artifact@v4
        with:
          name: releases

      - name: Upload releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Releases"
          files: |
            *.zip
            *.tar.gz
              